export { default as GoogleAuthButton } from './GoogleAuthButton.vue'
export { default as VkAuthButton } from './VkAuthButton.vue'
export { default as AppleAuthButton } from './AppleAuthButton.vue'
export { default as FacebookAuthButton } from './FacebookAuthButton.vue'
export { default as LandingHeader } from './LandingHeader.vue'
export { default as LandingFooter } from './LandingFooter.vue'
export { default as LandingSlider } from './LandingSlider.vue'
