export { default as LandingPage } from './LandingPage/LandingPage.vue'
export { default as ErrorPage } from './ErrorPage/ErrorPage.vue'
export { default as ProjectView } from './ProjectView/ProjectView.vue'
export { default as VacanciesView } from './VacanciesView/VacanciesView.vue'
export { default as UserView } from './UserView/UserView.vue'
export { default as ProjectsListView } from './ProjectsListView/ProjectsListView.vue'
export { default as NewProjectView } from './NewProjectView/NewProjectView.vue'
export { default as MainView } from './MainView/MainView.vue'
