export { default as PostAuthor } from './PostAuthor.vue'
export { default as PostButtons } from './PostButtons.vue'
export { default as PostComment } from './PostComment.vue'
export { default as PostText } from './PostText.vue'
export { default as PostGallery } from './PostGallery.vue'
