export { default as PostButtons } from './PostButtons.vue'
export { default as PostComment } from './PostComment.vue'
export { default as PostText } from './PostText.vue'
export { default as PostGallery } from './PostGallery.vue'
export { default as PostHeader } from './PostHeader.vue'
