export { default as GeneralSettings } from './generalSettings/GeneralSettings.vue'
export { default as Header } from './header/Header.vue'
export { default as Post } from './post/Post.vue'
export { default as ProfileSettings } from './profileSettings/ProfileSettings.vue'
export { default as Settings } from './settings/Settings.vue'
