export { default as Search } from './Search.vue'
export { default as Tabs } from './Tabs.vue'
export { default as Profile } from './Profile.vue'
export { default as ProfilePopup } from './ProfilePopup.vue'
export { default as Notifications } from './Notifications.vue'
export { default as NotificationsPopup } from './NotificationsPopup.vue'
